language: node_js
node_js: stable


before_install:
    - npm install hexo-cli -g
    - cd ../../
    - git clone ${Generate_REF} wongside/Hexo-generate-blog
    - ls wongside/Blog
    # - mkdir wongside/Hexo-generate-blog/public
    - cp -rf wongside/Blog/* wongside/Hexo-generate-blog/source/_posts/
    - cd wongside/Hexo-generate-blog/

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo g
  # - hexo d

after_script: 
  - git clone ${GT_REF} hexo-public
  - cp -rf public/* hexo-public/
  - ls public
  - ls source/_posts
  - ls hexo-public
  - cd hexo-public
  - git config user.name "wongside"
  - git config user.email "wongside@163.com"
  - git add .
  - git commit -am "Travis CI Auto Builder..."
  - git push origin master 

branches:
  only:
    - master
env:
 global:
   - GT_REF: https://wongside:${gitee_token}@gitee.com/wongside/wongside.git # gitee
   - GH_REF: https://${github_token}@github.com/wongside/wongside.github.io.git # github
   - Generate_REF: https://${github_token}@github.com/wongside/Hexo-generate-blog.git
