on:
  push:
    branches:
      - master

env:
  GIT_USER: Side
  GIT_EMAIL: sidew@qq.com
  DEPLOY_REPO: wongside/wongside.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout Blog
        uses: actions/checkout@v2
        with:
          path: Blog-file

      - name: Checkout Hexo repo
        uses: actions/checkout@v2
        with:
          repository: wongside/Hexo-generate-blog
          path: Hexo-generate-blog

      - name: Checkout html repo
        uses: actions/checkout@v2
        with:
          repository: wongside/wongside.github.io
          path: wongside.github.io

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          
      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Delete unused files
        working-directory: Blog-file
        run: |
          ls -al
          rm -rf .git
          rm -rf .github

      - name: Install hexo
        working-directory: Hexo-generate-blog
        run: |
          ls -al
          npm install hexo-cli -g --no-optional
          npm install --no-optional
          npm install --save hexo-theme-fluid

      - name: Generate Hexo
        working-directory: Hexo-generate-blog
        run: |
          mkdir -p source/_posts/
          cp -rf ../Blog-file/* source/_posts/
          npx hexo clean
          npx hexo g
          cp -rf public/* ../wongside.github.io/

      - name: Git commit
        working-directory: wongside.github.io
        run: |
          git add .
          git commit -m "auto generate hexo blog by github actions"

      - name: Update github repo
        working-directory: wongside.github.io
        run: |
          git remote set-url origin git@github.com:wongside/wongside.github.io.git
          git push origin master

      - name: Update gitee repo
        working-directory: wongside.github.io
        run: |
          git remote set-url origin git@gitee.com:wongside/wongside.git
          git push origin master