on:
  push:
    branches:
      - master

env:
  GIT_USER: Side
  GIT_EMAIL: sidew@qq.com
  DEPLOY_REPO: wongside/wongside.github.io
  DEPLOY_BRANCH: master

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [12.x]

    steps:
      - name: Checkout Blog
        uses: actions/checkout@v2

      - name: Checkout Hexo repo
        uses: actions/checkout@v2
        with:
          repository: wongside/Hexo-generate-blog
          path: Hexo-generate-blog

#       - name: Checkout theme repo
#         uses: actions/checkout@v2
#         with:
#           repository: ${{ env.THEME_REPO }}
#           ref: ${{ env.THEME_BRANCH }}
#           path: themes/concise

#       - name: Checkout deploy repo
#         uses: actions/checkout@v2
#         with:
#           repository: ${{ env.DEPLOY_REPO }}
#           ref: ${{ env.DEPLOY_BRANCH }}
#           path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          
      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: test
        working-directory: Hexo-generate-blog
        run: pwd

      - name: Install hexo
        working-directory: ../Hexo-generate-blog
        run: |
             npm install hexo-cli -g --no-optional
             npm install --no-optional
             ls -al
             npx hexo g
#      - name: test
#        working-directory: build
#        run: |
#            pwd
#            ls Hexo-generate-blog
#            npx hexo init
#            npx hexo g
#      - run: ls -al
#
#      - name: test
#        run: pwd
#
#      - run: ls
#      - run: cd ..
#      - run: ls
